### ISSUE TITLE
where is the Book file ?

### ISSUE THREAD

**Issue by tissatussa** [cimarronOST/Monolith#14]
In the UCI options i see Monolith can use a book file called Monolith.bin .. where can i get it ?

**Comment by tissatussa** [comment]
Your README states that PolyGlot opening books can be used, so i guess "Monolith.bin" can be any .bin opening book. However, some engines have their own opening book, and for me this is intended by the name "Monolith.bin", but probably i'm wrong.

**Comment by cimarronOST** [comment]
Yes you are right, Monolith can internally use PolyGlot opening books, the easiest way to use one is by putting a book in the same directory as the engine and naming it "Monolith.bin" and the engine will automatically use it. I've never provided nor created such a book, but you could find some generic books in the Forum Post section in [the Polyglot entry of the chess-programming wiki](https://www.chessprogramming.org/PolyGlot).
Nowadays the opening book is usually managed by the GUI that runs the engine, so I doubt anybody even uses the internal book option of engines anyways.
